---

- name: install rbenv
  homebrew:
    name: rbenv
    state: present
    update_homebrew: yes

- name: shellrc varaibles
  lineinfile:
    path: "{{silhouette_shellrc}}"
    regexp: "^eval.*rbenv init"
    line: 'eval "$(rbenv init -)"'
    mode: 0640

- name: install ruby
  command: "rbenv install -s {{rbenv_ruby_version}}"

- name: set global
  command: "rbenv global {{rbenv_ruby_version}}"
