#!/usr/bin/env bash

ROOT_DIR="${HOME}/.silhouette"

function remote_install() {
    git clone git remote git@github.com:mindmorass/silhouette.git $ROOT_DIR
}

function help() {
    echo "silhouette [OPTION]"
    printf "\n%s:\n" "OPTIONS" 
    printf "  %s\n" "help"
    printf "  %s\n" "install"
    printf "  %s\n" "update"
    printf "  %s\n" "build"
    printf "  %s\n" "test"
}

function update() {
    if [ -d $ROOT_DIR ]; then
	cd $ROOT_DIR
	git pull 
    fi
}

case "${1}" in
    install)
	remote_install	
	;;
    build)
	cd $ROOT_DIR
	ansible-playbook main.yml
	;;
    update)
	update
	;;
    test)
	# probably a combination of ansible tests and
	# BATS tests, need to give this a little more thought
	echo "Future for profile testing"
	;;
    *)
	help
	exit 2
	;;
esac

exit 0
